Refactor base indicator classes
Ouranosinc/xclim pull request #1446
Opened 2023-07-31 18:13 UTC by aulemahal

### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #1263
- [ ] Tests for the changes have been added (for bug fixes / features)
  - [x] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [x] CHANGES.rst has been updated (with summary of main changes)
  - [x] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added

### What kind of change does this PR introduce?

Move around some of the base indicator classes code. Split the missing values handling from the resampling handling. This way, indicators like `return_level` can reduce the full time axis and still perform some missing values handling.

### Does this PR introduce a breaking change?
No, not yet.

### Other information:
@huard @RondeauG, if I am not mistaken, `return_level` and `fit` currently have missing values handling disabled because it was impossible with the previous classes to have both this and full reduction of "time". Now that it is possible, should we activate it ? 

Similarly, `stats` had the "Any" missing method forced. Is there a reason for that ? Here, I removed the argument, meaning it will use "from_context".

2023-07-31 18:17 UTC, RondeauG commented
> if I am not mistaken, `return_level` and `fit` currently have missing values handling disabled because it was impossible with the previous classes to have both this and full reduction of "time". Now that it is possible, should we activate it ?
> 
> Similarly, `stats` had the "Any" missing method forced. Is there a reason for that ? Here, I removed the argument, meaning it will use "from_context".

Absolutely ! For all 3, having full control on the `missing` argument would be a great quality-of-life change.

2023-08-14 14:24 UTC, huard requested changes

2023-08-14 14:24 UTC, huard commented on xclim/core/calendar.py
> +def offset_is_divisor(freqA: str, freqB: str):
I suggest using descriptive names for freqA and freqB. 
freqA -> divisor
freqB -> freq

Also, the function name could be `is_offset_divisor`, to emulate other `is_condition` functions found elsewhere.

2023-08-14 14:24 UTC, huard commented on xclim/core/indicator.py
> +    To enable resampling, the :py:meth:`_get_missing_freq` method can be subclassed to return the resampling frequency. The method is always called with the indicator parameters.
Now that I've read the code I understand this comment, but it was cryptic on the first pass. 

It feels semantically weird that CheckMissingIndicator would be defined as an Indicator reducing the time dimension, but that ResamplingIndicator would then subclass it and revert that property. 

Should we bake missing values checks directly inside `Indicator` now that we're able to support them everywhere?

2023-08-31 20:48 UTC, huard approved these changes

2023-08-31 21:16 UTC, merged

2023-09-18 18:11 UTC, huard commented
Issue https://github.com/CSHS-CWRA/RavenPy/issues/307 is probably due to the fact that this PR made `fit` a subclass of `ReducingIndicator`. It was previously a subclass of `Indicator`, which has no missing value logic in it. 

So the generic `fit` indicator essentially went from skipping missing value checks, to apply the missing algorithm from context (typically `any`). I think we should have highlighted this more clearly in the release notes.