Add Christmas Day indices
Ouranosinc/xclim pull request #2030
Opened 2024-12-19 22:53 UTC by Zeitsperre

### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #2029 
- [ ] Tests for the changes have been added (for bug fixes / features)
  - [ ] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [ ] CHANGELOG.rst has been updated (with summary of main changes)
  - [ ] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added

### What kind of change does this PR introduce?

* Adds two new indices:
  * `holiday_snow_days`
  * `holiday_snow_and_snowfall_days`

### Does this PR introduce a breaking change?

No.

### Other information:

These indices are currently designed to return a boolean array, i.e. if December 25th (or the range of days asked for) satisfy the requirements, the time step at the frequency provided is marked `True`. 

There's also the idea of using the `days_with_snow` indice by passing a date-constrained snow depth array to it. I'm not sure which approach is ideal.

2024-12-20 20:56 UTC, Zeitsperre commented
This is just waiting on https://github.com/Ouranosinc/xclim-testdata/pull/30

2025-01-08 16:52 UTC, aulemahal requested changes

2025-01-08 16:52 UTC, aulemahal commented on src/xclim/indices/_threshold.py
> +        .map(lambda x: x.sum(dim="time"))
```suggestion
        .sum()
```

2025-01-08 16:52 UTC, aulemahal commented on src/xclim/indices/_threshold.py
> +        .map(lambda x: x.sum(dim="time"))
```suggestion
        .sum()
```

2025-01-08 16:52 UTC, aulemahal commented on src/xclim/indicators/land/_snow.py
> +    units="1",
```suggestion
    units="days",
```
The output is a number of days, shouldn't units be "days" ?

2025-01-08 16:52 UTC, aulemahal commented on src/xclim/indicators/land/_snow.py
> +    units="1",
Same as above.
```suggestion
    units="days",
```

2025-01-08 17:37 UTC, Zeitsperre commented on src/xclim/indicators/land/_snow.py
> +    units="1",
Right. Forgot to change this. Thanks!

2025-01-08 22:05 UTC, Zeitsperre commented
One thing I'm wondering about are the names of these indices/indicators. Given that they can accept an `indexer`, would it make more sense to general the `indices` more and rename the indicators to use "Christmas" as well as hardcode them to December 25th?

@tlogan2000 any opinions on this?

2025-01-08 22:54 UTC, aulemahal commented
If you hardcode the date to a specific date, then there's no need for a compute function, you could simple use `generic.count_occurrences`. And I would argue that the more general version of `holidays_snow_days` is  `snd_days_above`.

I think generalizing `holidays_snow_and_snowfall_days` would best be done by implementing a `count_multivariate_occurrences`.

2025-01-09 22:39 UTC, aulemahal commented on src/xclim/data/fr.json
> +    "abstract": "Nombre de jours de neige et de jours de chute de neige durant les jours fériés."
```suggestion
    "long_name": "Nombre de jours de neige durant les jours de Noël",
    "description": "Nombre de jours de neige durant les jours de Noël.",
    "title": "Jours de neige durant les jours de Noël",
    "abstract": "Nombre de jours de neige durant les jours de Noël."
  },
  "HOLIDAY_SNOW_AND_SNOWFALL_DAYS": {
    "long_name": "Nombre de jours de neige et de jours de chute de neige durant les jours de Noël",
    "description": "Nombre de jours de neige et de jours de chute de neige durant les jours de Noël.",
    "title": "Jours de neige et de chute de neige durant les jours de Noël",
    "abstract": "Nombre de jours de neige et de jours de chute de neige durant les jours de Noël."
```
Pas certain ici. "durant les fêtes" ? "durant Noël" ?
« Jours fériés » includes any day without work, it's a bit too general.

2025-01-09 22:39 UTC, aulemahal commented on src/xclim/indices/_threshold.py
> +        drop=True,
```suggestion
```
I don't know if that's the source of your error, but I would avoid dropping when it is not needed. Changing the size of an array sometimes introduces bugs with dask.

2025-01-09 22:39 UTC, aulemahal commented on src/xclim/indices/_threshold.py
> +        drop=True,
```suggestion
```
same.

2025-01-09 22:39 UTC, aulemahal commented on src/xclim/indices/_threshold.py
> +        Threshold snowfall flux. Default: 1 mm.
```suggestion
        Threshold daily snowfall liquid-water equivalent thickness. Default: 1 mm.
```
1 mm is not a flux, it is a liquid-water equivalent thickness!

2025-01-09 22:39 UTC, aulemahal commented on src/xclim/indices/_threshold.py
> +    prsn_thresh: Quantified = "1 cm",
```suggestion
    prsn_thresh: Quantified = "1 mm",
```

2025-01-09 22:39 UTC, aulemahal commented on src/xclim/indices/_threshold.py
> +        Threshold snowfall flux. Default: 1 mm.
You'll note that this means the  `snd_thresh` is in actual thickness and `prsn_thresh` is in liquid-water equivalent thickness. Welcome to the world of snow.

2025-01-09 22:39 UTC, aulemahal commented on src/xclim/indices/_threshold.py
> +        drop=True,
```suggestion
```
Same as above.

2025-01-09 22:39 UTC, aulemahal commented on src/xclim/indices/_threshold.py
> +    xmas_days = xmas_days.assign_attrs({"units": "days"})
```suggestion
    xmas_days = to_agg_units(xmas_days, snd,  "count")
```
This will put the correct units, depending on the sampling frequency of the data. I know your function assumes daily, but the explicit check is only done on the indicator. Thus, the function should still be able to manage other samplings.

2025-01-09 22:39 UTC, aulemahal commented on src/xclim/indices/_threshold.py
> +    perfect_xmas_days = perfect_xmas_days.assign_attrs({"units": "days"})
```suggestion
    perfect_xmas_days = to_agg_units(perfect_xmas_days, snd, "count")
```
Same as above.

2025-01-10 16:07 UTC, Zeitsperre commented on src/xclim/indices/_threshold.py
> +        Threshold snowfall flux. Default: 1 mm.
Thanks, I hate it.

For the `prsn` indicator, ECCC mentions the term "measurable snowfall", which gives me the impression that it needs to be enough to not be considered a trace amount.

If we look at [January 2024 at YUL](https://climate.weather.gc.ca/climate_data/daily_data_e.html?timeframe=2&hlyRange=2013-02-13%7C2025-01-09&dlyRange=2013-02-14%7C2025-01-09&mlyRange=%7C&StationID=51157&Prov=QC&urlExtension=_e.html&searchType=stnName&optLimit=yearRange&StartYear=1840&EndYear=2025&selRowPerPage=25&Line=4&searchMethod=contains&txtStationName=montreal&time=LST&Day=9&Year=2024&Month=1#) or other months, the smallest increment above 0.0 cm seems to be 0.4 cm of snow (not swe).

We have the `snd_to_snw` conversion for estimating the amount based on the density of snow. Would it make sense to use taht here?

2025-01-10 16:26 UTC, Zeitsperre commented on src/xclim/indices/_threshold.py
> +        Threshold snowfall flux. Default: 1 mm.
I know that this is quite complex for a Friday afternoon indicator, but What if we were to convert as follows:
```python
snw_equivalent = convert_units_to(prsn, "kg m-2")
snd_from_falling_snow = snw_to_snd(snw_equivalent)
cond = snd_from_falling_snow > prsn_thresh
```

It would probably make sense to rename `prsn_thresh` in this case...

2025-01-10 17:24 UTC, aulemahal commented on src/xclim/indices/_threshold.py
> +        Threshold snowfall flux. Default: 1 mm.
I would argue against using `snw_to_snd` here has to not introduce the snow density uncertainty, better ask for a liquid water equivalent and let the user to it's own (mental) conversion ?

2025-01-14 21:09 UTC, aulemahal approved these changes

2025-01-14 21:34 UTC, merged